Support "RETRIEVE" statement in extended query protocol
The test case src/test/isolation2/test_parallel_retrieve_cursor_extended_query.c
only check the command RC to verify.

diff --git a/src/test/isolation2/Makefile b/src/test/isolation2/Makefile
--- a/src/test/isolation2/Makefile
+++ b/src/test/isolation2/Makefile
@@ -17,9 +17,12 @@ endif
 override CPPFLAGS := -I$(srcdir) -I$(libpq_srcdir) -I$(srcdir)/../regress $(CPPFLAGS)
 override LDLIBS := $(libpq_pgport) $(LDLIBS)
 
-all: test_python pg_isolation2_regress$(X) all-lib extended_protocol_test
+all: test_python pg_isolation2_regress$(X) all-lib extended_protocol_test test_parallel_retrieve_cursor_extended_query
 
 extended_protocol_test: extended_protocol_test.c
+	$(CC) $(CPPFLAGS) -I$(top_builddir)/src/interfaces/libpq -L$(GPHOME)/lib -L$(top_builddir)/src/interfaces/libpq  -o $@ $< -lpq
+
+test_parallel_retrieve_cursor_extended_query: test_parallel_retrieve_cursor_extended_query.c
 	$(CC) $(CPPFLAGS) -I$(top_builddir)/src/interfaces/libpq -L$(GPHOME)/lib -L$(top_builddir)/src/interfaces/libpq  -o $@ $< -lpq
 
 test_python:
@@ -76,8 +79,11 @@ installcheck-parallel-retrieve-cursor-check-segments:
 installcheck-parallel-retrieve-cursor: install installcheck-parallel-retrieve-cursor-check-segments
 	# TODO: Orca is not support by PARALLEL RETRIEVE CURSOR for now. Remove the optimizer
 	# setting when it is supported.
-	# before running test, set statement_timeout to 1 minute so that even if some
+	#
+	# Before running test, set statement_timeout to 1 minute so that even if some
 	# error make 'gp_wait_parallel_retrieve_cursor()' hang, it will be canceled when timeout.
+	#
+	# And also add test for test_parallel_retrieve_cursor_extended_query, only need to check command rc==0
 	default_optimizer=$$(gpconfig -s optimizer | grep "Master" | cut -d':' -f2) && \
 	default_master_timeout=$$(gpconfig -s statement_timeout | grep "Master" | cut -d':' -f2) && \
 	default_segment_timeout=$$(gpconfig -s statement_timeout | grep "Segment" | cut -d':' -f2) && \
@@ -93,9 +99,16 @@ installcheck-parallel-retrieve-cursor: install installcheck-parallel-retrieve-cu
 	gpconfig -s statement_timeout && \
 	./pg_isolation2_regress $(EXTRA_REGRESS_OPTS) --init-file=$(top_builddir)/src/test/regress/init_file --init-file=./init_file_parallel_retrieve_cursor --bindir='$(bindir)' --inputdir=$(srcdir) --dbname=isolation2parallelretrcursor --schedule=$(srcdir)/parallel_retrieve_cursor_schedule ; \
 	ret=$$? ; \
+	./test_parallel_retrieve_cursor_extended_query "gpadmin" "postgres" > test_parallel_retrieve_cursor_extended_query.log 2>&1 ; \
+	ret2=$$? ; \
+	if [ "$${ret2}" == 0 ]; then \
+		echo "[PASS]: test_parallel_retrieve_cursor_extended_query test pass. See test_parallel_retrieve_cursor_extended_query.log.\n"; \
+	else \
+		echo "[ERROR]: test_parallel_retrieve_cursor_extended_query test failed. See test_parallel_retrieve_cursor_extended_query.log.\n"; \
+	fi; \
 	gpconfig -c optimizer -v $${default_optimizer} -m $${default_optimizer} && \
 	gpconfig -c statement_timeout -v $${default_segment_timeout} -m $${default_master_timeout} && \
 	gpstop -u && \
 	gpconfig -s optimizer && \
 	gpconfig -s statement_timeout && \
-	exit $${ret}
+	exit "$$(( $${ret} || $${ret2} ))"
